# Generated by Django 6.0.2 on 2026-02-18 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow_app', '0003_meetingsession_onlineuser_useractivity_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('total_meetings', models.IntegerField(default=0)),
                ('meetings_today', models.IntegerField(default=0)),
                ('total_meeting_minutes', models.BigIntegerField(default=0)),
                ('total_teams', models.IntegerField(default=0)),
                ('teams_created_today', models.IntegerField(default=0)),
                ('total_logins_today', models.IntegerField(default=0)),
                ('peak_concurrent_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('analytics_admin', 'Analytics Admin'), ('support_admin', 'Support Admin'), ('moderator', 'Moderator')], default='moderator', max_length=50)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_teams', models.BooleanField(default=False)),
                ('can_view_all_meetings', models.BooleanField(default=False)),
                ('can_delete_content', models.BooleanField(default=False)),
                ('can_manage_admins', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
            },
        ),
    ]
